---
apiVersion: v1
kind: Namespace
metadata:
  name: naasgul
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: naasgul
  namespace: naasgul
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: naasgul
rules:
- apiGroups:
  - ""
  resources:
  - ""
  verbs:
  - ""
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: naasgul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: naasgul
subjects:
- kind: ServiceAccount
  name: naasgul
  namespace: naasgul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naasgul_api
  namespace: naasgul
  labels:
    k8s-app: naasgul_api
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: naasgul_api
  template:
    metadata:
      labels:
        k8s-app: naasgul_api
    spec:
      containers:
      - name: naasgul
        image: naasgul_api:latest
        #args: ["/naasgul"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_STRING
          value: "mongodb://mongodb:27017/"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naasgul_topo_scrapper
  namespace: naasgul
  labels:
    k8s-app: naasgul_topo_scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: naasgul_topo_scrapper
  template:
    metadata:
      labels:
        k8s-app: naasgul_topo_scrapper
    spec:
      containers:
      - name: naasgul
        image: naasgul_topo_scrapper_snmp:latest
        #args: ["/naasgul"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_STRING
          value: "mongodb://mongodb:27017/"
        - name: LLDP_INIT_NODE_FQDN
          value: "" # CI_VAR to add here
        - name: LLDP_INIT_NODE_IP
          value: "" # CI_VAR to add here
        - name: LLDP_INIT_NODE_PORT=161
          value: "" # CI_VAR to add here
        - name: LLDP_STOP_NODES_FQDN=
          value: "" # CI_VAR to add here
        - name: LLDP_STOP_NODES_IP=
          value: "" # CI_VAR to add here
        - name: SNMP_USER
          valueFrom:
          secretKeyRef:
            name: snmp_user
            key: snmp_user
          # kubectl create secret generic db-user-pass \
          #         --from-literal=username=devuser \
          #         --from-literal=password='S!B\*d$zDsb='
        - name: SNMP_AUTH_PWD
          valueFrom:
          secretKeyRef:
            name: snmp_auth_pwd
            key: snmp_auth_pwd
        - name: SNMP_PRIV_PWD
          valueFrom:
          secretKeyRef:
            name: snmp_priv_pwd
            key: snmp_priv_pwd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naasgul_stats_scrapper
  namespace: naasgul
  labels:
    k8s-app: naasgul_stats_scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: naasgul_stats_scrapper
  template:
    metadata:
      labels:
        k8s-app: naasgul_stats_scrapper
    spec:
      containers:
      - name: naasgul
        image: naasgul_stats_crawler_snmp:latest
        #args: ["/naasgul"]
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_STRING
          value: "mongodb://mongodb:27017/"
        - name: SNMP_USER
          valueFrom:
          secretKeyRef:
            name: snmp_user
            key: snmp_user
        - name: SNMP_AUTH_PWD
          valueFrom:
          secretKeyRef:
            name: snmp_auth_pwd
            key: snmp_auth_pwd
        - name: SNMP_PRIV_PWD
          valueFrom:
          secretKeyRef:
            name: snmp_priv_pwd
            key: snmp_priv_pwd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naasgul_frontend
  namespace: naasgul
  labels:
    k8s-app: naasgul_frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: naasgul_frontend
  template:
    metadata:
      labels:
        k8s-app: naasgul_frontend
    spec:
      containers:
      - name: naasgul
        image: naasgul_frontend:latest
        #args: ["/naasgul"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
          - containerPort: 80
