FROM python:3.9.6-slim-buster

COPY api_for_frontend.py db_layer.py requirements.txt /app/

WORKDIR /app

RUN pip install -r requirements.txt

CMD ["uvicorn", "api_for_frontend:app", "--host", "0.0.0.0", "--port", "80"]
