FROM python:3.8.10-slim-buster

COPY snmp_get_ifaces_stats.py snmp_functions.py db_layer.py requirements.txt /app/

WORKDIR /app

#RUN pip uninstall -y bson \
#    && pip uninstall -y pymongo \
#    && pip install -r requirements.txt

RUN pip install -r requirements.txt

CMD ["python", "snmp_get_ifaces_stats.py"]
